export default (scorllTop, headerdom) => {
    if (scorllTop < 10) {
        headerdom.classList.add('headershow0', 'backwhite0', 'carWhite0')
        headerdom.classList.remove(
            'headershow1',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite1',
            'backwhite2',
            'backwhite3',
            'backwhite4',
            'backwhite5',
            'carWhite1',
            'carWhite2',
            'carWhite3',
            'carWhite4',
            'carWhite5',
            'defaultimg'
        )
    } else if (scorllTop >= 10 && scorllTop < 30) {
        headerdom.classList.add('headershow1', 'backwhite1', 'carWhite1')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite0',
            'backwhite2',
            'backwhite3',
            'backwhite4',
            'backwhite5',
            'carWhite0',
            'carWhite2',
            'carWhite3',
            'carWhite4',
            'carWhite5',
            'defaultimg'
        )
    } else if (scorllTop >= 30 && scorllTop < 50) {
        headerdom.classList.add('headershow2', 'backwhite2', 'carWhite2')
        headerdom.classList.remove(
            'headershow0',
            'headershow1',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite0',
            'backwhite1',
            'backwhite3',
            'backwhite4',
            'backwhite5',
            'carWhite0',
            'carWhite1',
            'carWhite3',
            'carWhite4',
            'carWhite5'
        )
    } else if (scorllTop >= 50 && scorllTop < 70) {
        headerdom.classList.add('headershow3', 'backwhite3', 'carWhite3')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow1',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite0',
            'backwhite1',
            'backwhite2',
            'backwhite4',
            'backwhite5',
            'carWhite0',
            'carWhite1',
            'carWhite2',
            'carWhite4',
            'carWhite5'
        )
    } else if (scorllTop >= 70 && scorllTop < 90) {
        headerdom.classList.add('headershow4', 'backwhite4', 'carWhite4')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow1',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite0',
            'backwhite1',
            'backwhite2',
            'backwhite3',
            'backwhite5',
            'carWhite0',
            'carWhite1',
            'carWhite2',
            'carWhite3',
            'carWhite5'
        )
    } else if (scorllTop >= 90 && scorllTop < 110) {
        headerdom.classList.add('headershow5', 'backwhite5', 'carWhite5')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow1',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite0',
            'backwhite1',
            'backwhite2',
            'backwhite3',
            'backwhite4',
            'carWhite0',
            'carWhite1',
            'carWhite2',
            'carWhite3',
            'carWhite4'
        )
    } else if (scorllTop >= 130 && scorllTop < 150) {
        headerdom.classList.add('headershow6')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow1',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow10',
            'backwhite5',
            'carWhite5'
        )
    } else if (scorllTop >= 170 && scorllTop < 190) {
        headerdom.classList.add('headershow7')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow1',
            'headershow8',
            'headershow9',
            'headershow10'
        )
    } else if (scorllTop >= 190 && scorllTop < 210) {
        headerdom.classList.add('headershow8')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow1',
            'headershow9',
            'headershow10'
        )
    } else if (scorllTop >= 210 && scorllTop < 230) {
        headerdom.classList.add('headershow9')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow1',
            'headershow10'
        )
    } else if (scorllTop >= 230) {
        headerdom.classList.add('headershow10')
        headerdom.classList.remove(
            'headershow0',
            'headershow2',
            'headershow3',
            'headershow4',
            'headershow5',
            'headershow6',
            'headershow7',
            'headershow8',
            'headershow9',
            'headershow1',
            'backwhite0',
            'backwhite1',
            'backwhite2',
            'backwhite3',
            'backwhite4',
            'backwhite5',
            'carWhite0',
            'carWhite1',
            'carWhite2',
            'carWhite3',
            'carWhite4',
            'carWhite5'
        )
    }
}